###############################################################
# Dockerfile generated by Bocker-v1.3. Do not edit this file. #
###############################################################

FROM debian:wheezy
MAINTAINER My name <myemail@example.net>

ENV DEBIAN_FRONTEND noninteractive

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Here is from `__ed_before_ship` method. You may need your own
# custom one to advance the base image when it doesn't have Bash.
#
# The default `__ed_before_ship` method is to print this message.
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Bocker method => __ed_ship
# * The output is /bocker.sh in the result image.
# * List of methods:
#   - ed_apt_clean
#   - ed_apt_purge
#
# | set -eux
# | if [ -f '/bocker.sh' ]; then source '/bocker.sh'; fi
# | ed_apt_clean () 
# | { 
# |     rm -fv /var/cache/apt/*.bin;
# |     rm -fv /var/cache/apt/archives/*.*;
# |     rm -fv /var/lib/apt/lists/*.*;
# |     apt-get autoclean
# | }
# | ed_apt_purge () 
# | { 
# |     apt-get purge -y --auto-remove $@;
# |     ed_apt_clean
# | }
# | echo '#!/usr/bin/env bash' > '/bocker.sh'
# | echo '# This file is generated by Bocker.' >> '/bocker.sh'
# | declare -f >> '/bocker.sh'
# | echo 'if [ -n "$@" ]; then $@; fi; ' >> '/bocker.sh'
# | chmod 755 '/bocker.sh'
#
RUN echo \
c2V0IC1ldXgKaWYgWyAtZiAnL2JvY2tlci5zaCcgXTsgdGhlbiBzb3VyY2UgJy9ib2NrZXI\
uc2gnOyBmaQplZF9hcHRfY2xlYW4gKCkgCnsgCiAgICBybSAtZnYgL3Zhci9jYWNoZS9hcH\
QvKi5iaW47CiAgICBybSAtZnYgL3Zhci9jYWNoZS9hcHQvYXJjaGl2ZXMvKi4qOwogICAgc\
m0gLWZ2IC92YXIvbGliL2FwdC9saXN0cy8qLio7CiAgICBhcHQtZ2V0IGF1dG9jbGVhbgp9\
CmVkX2FwdF9wdXJnZSAoKSAKeyAKICAgIGFwdC1nZXQgcHVyZ2UgLXkgLS1hdXRvLXJlbW9\
2ZSAkQDsKICAgIGVkX2FwdF9jbGVhbgp9CmVjaG8gJyMhL3Vzci9iaW4vZW52IGJhc2gnID\
4gJy9ib2NrZXIuc2gnCmVjaG8gJyMgVGhpcyBmaWxlIGlzIGdlbmVyYXRlZCBieSBCb2NrZ\
XIuJyA+PiAnL2JvY2tlci5zaCcKZGVjbGFyZSAtZiA+PiAnL2JvY2tlci5zaCcKZWNobyAn\
aWYgWyAtbiAiJEAiIF07IHRoZW4gJEA7IGZpOyAnID4+ICcvYm9ja2VyLnNoJwpjaG1vZCA\
3NTUgJy9ib2NrZXIuc2gnCg==\
  | base64 -d | /usr/bin/env bash

# Bocker method => ed_install_curl
#
# | set -eux
# | if [ -f '/bocker.sh' ]; then source '/bocker.sh'; fi
# | ed_install_curl () 
# | { 
# |     apt-get update;
# |     apt-get install -y curl;
# |     ed_apt_clean
# | }
# | ed_install_curl
#
RUN echo \
c2V0IC1ldXgKaWYgWyAtZiAnL2JvY2tlci5zaCcgXTsgdGhlbiBzb3VyY2UgJy9ib2NrZXI\
uc2gnOyBmaQplZF9pbnN0YWxsX2N1cmwgKCkgCnsgCiAgICBhcHQtZ2V0IHVwZGF0ZTsKIC\
AgIGFwdC1nZXQgaW5zdGFsbCAteSBjdXJsOwogICAgZWRfYXB0X2NsZWFuCn0KZWRfaW5zd\
GFsbF9jdXJsCg==\
  | base64 -d | /usr/bin/env bash

# Bocker methods:
# - ed_group_part_1
# - ed_group_part_2
#
# | set -eux
# | if [ -f '/bocker.sh' ]; then source '/bocker.sh'; fi
# | ed_group_part_1 () 
# | { 
# |     echo "This is part 1 of the group."
# | }
# | ed_group_part_2 () 
# | { 
# |     echo "This is part 2 of the group."
# | }
# | ed_group_part_1
# | ed_group_part_2
#
RUN echo \
c2V0IC1ldXgKaWYgWyAtZiAnL2JvY2tlci5zaCcgXTsgdGhlbiBzb3VyY2UgJy9ib2NrZXI\
uc2gnOyBmaQplZF9ncm91cF9wYXJ0XzEgKCkgCnsgCiAgICBlY2hvICJUaGlzIGlzIHBhcn\
QgMSBvZiB0aGUgZ3JvdXAuIgp9CmVkX2dyb3VwX3BhcnRfMiAoKSAKeyAKICAgIGVjaG8gI\
lRoaXMgaXMgcGFydCAyIG9mIHRoZSBncm91cC4iCn0KZWRfZ3JvdXBfcGFydF8xCmVkX2dy\
b3VwX3BhcnRfMgo=\
  | base64 -d | /usr/bin/env bash

COPY enabled/test.txt /example/

# Bocker method => __ed_ship
# * The output is /bocker.sh in the result image.
# * List of methods:
#   - ed_ship_later_example
#
# | set -eux
# | if [ -f '/bocker.sh' ]; then source '/bocker.sh'; fi
# | ed_ship_later_example () 
# | { 
# |     echo "This is an example.";
# |     echo "This is shipped at the end of Dockerfile.";
# |     echo 'Quoting example.'
# | }
# | echo '#!/usr/bin/env bash' > '/bocker.sh'
# | echo '# This file is generated by Bocker.' >> '/bocker.sh'
# | declare -f >> '/bocker.sh'
# | echo 'if [ -n "$@" ]; then $@; fi; ' >> '/bocker.sh'
# | chmod 755 '/bocker.sh'
#
RUN echo \
c2V0IC1ldXgKaWYgWyAtZiAnL2JvY2tlci5zaCcgXTsgdGhlbiBzb3VyY2UgJy9ib2NrZXI\
uc2gnOyBmaQplZF9zaGlwX2xhdGVyX2V4YW1wbGUgKCkgCnsgCiAgICBlY2hvICJUaGlzIG\
lzIGFuIGV4YW1wbGUuIjsKICAgIGVjaG8gIlRoaXMgaXMgc2hpcHBlZCBhdCB0aGUgZW5kI\
G9mIERvY2tlcmZpbGUuIjsKICAgIGVjaG8gJ1F1b3RpbmcgZXhhbXBsZS4nCn0KZWNobyAn\
IyEvdXNyL2Jpbi9lbnYgYmFzaCcgPiAnL2JvY2tlci5zaCcKZWNobyAnIyBUaGlzIGZpbGU\
gaXMgZ2VuZXJhdGVkIGJ5IEJvY2tlci4nID4+ICcvYm9ja2VyLnNoJwpkZWNsYXJlIC1mID\
4+ICcvYm9ja2VyLnNoJwplY2hvICdpZiBbIC1uICIkQCIgXTsgdGhlbiAkQDsgZmk7ICcgP\
j4gJy9ib2NrZXIuc2gnCmNobW9kIDc1NSAnL2JvY2tlci5zaCcK\
  | base64 -d | /usr/bin/env bash

CMD /bin/true
